# Generated by Django 4.0.4 on 2022-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text_preview',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.IntegerField(choices=[(1, 'envoie'), (2, 'accepter'), (3, 'refuser')]),
        ),
    ]
