# Generated by Django 4.0.4 on 2022-05-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_tache_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='user',
        ),
        migrations.AddField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projet.project'),
        ),
    ]
