# Generated by Django 4.0.4 on 2022-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_tache_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='decision',
            field=models.IntegerField(choices=[(1, 'INACHEVE'), (2, 'NUL'), (3, 'PASSABLE'), (4, 'BIEN')], default=1),
            preserve_default=False,
        ),
    ]
